name: liqui
description: iOS-styled liquid sheets and buttons
version: 0.2.1
homepage: https://github.com/manudicri/liqui

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  elegant_spring_animation: ^2.0.2
  flutter:
    sdk: flutter
  screen_corner_radius: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
